#Compléter ce Makefile
CFLAGS = -Wall -Wextra -Wno-unused-function -Wno-unused-variable -g -O0 -Wl,-z,norelro -fno-PIC -z execstack -fno-stack-protector
LDFLAGS = -no-pie



clean:
	rm -f 
	rm -f *.o
